---
name: Industrial CI
on:
    workflow_call:
    workflow_dispatch:
    push:


jobs:
    black:
        name: Black
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: psf/black@stable
              with:
                  options: --line-length=99
    clang:
        name: Set up Clang
        steps:
            - uses: actions/checkout@v3
            - uses: egor-tensin/setup-clang@v1
              with:
                version: latest
                platform: x64

    ros_industrial_ci:
        name: ROS Industrial CI
        needs:
            - black
            - clang
        strategy:
            fail-fast: false
            matrix:
                ROS_DISTRO: [humble]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Clone installation requirements
              shell: bash
              run: git submodule update --init
            - uses: ros-industrial/industrial_ci@master
              env:
                  ROS_DISTRO: ${{matrix.ROS_DISTRO}}
